= Coding tasks

== This repository contains coding tasks and excercises for job interviews.

=== Task 1: Find the missing number in the array
You are given an array of positive numbers from 1 to n, such that all numbers from 1 to n are present except one number x.
You have to find x. The input array is not sorted. Look at the below array and give it a try before checking the solution.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Constant, _O(1)_

=== Task 2: Determine if the sum of two integers is equal to the given value.
Given an array of integers and a value, determine if there are any two integers in the array whose sum is equal to the given value. Return true if the sum exists and return false if it does not.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Constant, _O(n)_

=== Task 3: Merge two sorted linked lists
Given two sorted linked lists, merge them so that the resulting linked list is also sorted.

*Runtime Complexity*: Linear, _O(m+n)_ where _m_ and _n_ are lengths of both linked lists

*Memory Complexity*: Constant, _O(1)_

=== Task 4: Copy linked list with arbitrary pointer
You are given a linked list where the node has two pointers. The first is the regular next pointer. The second pointer is called arbitrary_pointer and it can point to any node in the linked list. Your job is to write code to make a deep copy of the given linked list. Here, deep copy means that any operations on the original list (inserting, modifying and removing) should not affect the copied list.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Linear, _O(n)_

=== Task 5: Level Order Traversal of Binary Tree
Given the root of a binary tree, display the node values at each level. Node values for all levels should be displayed on separate lines.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Linear, _O(n)_

=== Task 6: Determine if a binary tree is a binary search tree
Given a Binary Tree, figure out whether it’s a Binary Search Tree. In a binary search tree, each node’s key value is smaller than the key value of all nodes in the right subtree, and is greater than the key values of all nodes in the left subtree i.e. `L < N < RL < N < R`.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Linear, _O(n)_

=== Task 7: String segmentation
You are given a dictionary of words and a large input string. You have to find out whether the input string can be completely segmented into the words of a given dictionary.

*Runtime Complexity*: Exponential, _O(2^n)_ (with only recursion)
*Runtime Complexity*: Polynomial, _O(n^2)_ (with memoization)

*Memory Complexity*: Polynomial, _O(n^2)_

=== Task 8: Reverse Words in a Sentence
Reverse the order of words in a given sentence (an array of characters).

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Constant, _O(1)_

=== Task 9: Coin Changing Problem
Suppose we have coin denominations of [1, 2, 5] and the total amount is 7. We can make changes in the following 6 ways:
|===
|Number of ways to make a change

|1, 1, 1, 1, 1, 1, 1
|1, 1, 1, 1, 1, 2
|1, 1, 1, 2, 2
|1, 2, 2, 2
|1, 1, 5
|2, 5
|===

*Runtime Complexity*: Quadratic, _O(m*n)_ [m - number of denominations, n - total amount]

*Memory Complexity*: Linear, _O(n)_
