= Coding tasks

== This repository contains coding tasks and excercises for job interviews.

=== Task 1: Find the missing number in the array
You are given an array of positive numbers from 1 to n, such that all numbers from 1 to n are present except one number x.
You have to find x. The input array is not sorted. Look at the below array and give it a try before checking the solution.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Constant, _O(1)_

=== Task 2: Determine if the sum of two integers is equal to the given value.
Given an array of integers and a value, determine if there are any two integers in the array whose sum is equal to the given value. Return true if the sum exists and return false if it does not.

*Runtime Complexity*: Linear, _O(n)_

*Memory Complexity*: Constant, _O(n)_

=== Task 3: Merge two sorted linked lists
Given two sorted linked lists, merge them so that the resulting linked list is also sorted.

*Runtime Complexity*: Linear, _O(m+n)_ where _m_ and _n_ are lengths of both linked lists

*Memory Complexity*: Constant, _O(1)_
